#include <stdio.h>   
#include <openssl/rsa.h>
#include <curl/curl.h>
#include <openssl/x509v3.h>
#include <openssl/x509_vfy.h>
#include <openssl/crypto.h>
#include <openssl/lhash.h>
#include <openssl/evp.h>
#include <openssl/objects.h>
#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/pkcs12.h>
#include <openssl/bio.h>
#include <openssl/ssl.h>
#include <cstdio> 
#include <iostream>
#include <fstream>
#include <string>
#include <map>
#include <algorithm>
#include <fcntl.h>
#include <boost/filesystem.hpp>
#include <algorithm>
#include <functional>
#include <openssl/rsa.h>
#include <openssl/pem.h>
#define BUFSIZE 1024
